CREATE TABLE tbProdutos (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	Codigo varchar(20) NOT NULL UNIQUE,
	Descricao varchar(100) NOT NULL,
	Grupo varchar(10) NOT NULL,
	Preco float NOT NULL
);

CREATE TABLE tbClientes (
	CPF varchar(20) NOT NULL PRIMARY KEY,
	Nome varchar(10) NOT NULL,
	Cidade varchar(30) NOT NULL,
	Bairro varchar(30) NOT NULL
);

CREATE TABLE tbPedidos (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	Pedido varchar(20) NOT NULL UNIQUE,
	Data date NOT NULL,
	ClienteCPF varchar(20) NOT NULL,
	CONSTRAINT ClienteCPF_FK FOREIGN KEY (ClienteCPF) REFERENCES tbClientes(CPF)
);


CREATE TABLE tbPedidosItens (
	PedidoID int NOT NULL,
	ProdutoID int NOT NULL,
	Qtde int NOT NULL,
	Unitario float NOT NULL,
	Desconto float NOT NULL,
	CONSTRAINT PRODUTO_FK FOREIGN KEY (ProdutoID) REFERENCES tbProdutos(ID),
	CONSTRAINT PEDIDO_FK FOREIGN KEY (PedidoID) REFERENCES tbPedidos(ID)
);



/* *********************************************************** QUESTÃO 1 ********************************************************** */
/* ******************************************************************************************************************************** */

/* Questão 1 letra A */
INSERT INTO tbProdutos ( Codigo, Descricao, Grupo, Preco) VALUES ( '0001', 'Produto Teste 01', 'CELULARES', 30.00);

/* Questão 1 letra B */
INSERT INTO tbProdutos ( Codigo, Descricao, Grupo, Preco) VALUES ( '0002', 'Produto Teste 02', 'CELULARES', 35.00);

/* Questão 1 letra C */
INSERT INTO tbProdutos ( Codigo, Descricao, Grupo, Preco) VALUES ( '0003', 'Produto Teste 03', 'CAPAS', 40.00);

/* Questão 1 letra D */
INSERT INTO tbProdutos ( Codigo, Descricao, Grupo, Preco) VALUES ( '0004', 'Produto Teste 04', 'CAPAS', 45.00);

/* Questão 1 letra E */
INSERT INTO tbProdutos ( Codigo, Descricao, Grupo, Preco) VALUES ( '0005', 'Produto Teste 05', 'CELULARES', 50.00);

/* ******************************************************************************************************************************** */


/* *********************************************************** QUESTÃO 2 ********************************************************** */
/* ******************************************************************************************************************************** */

INSERT INTO tbClientes (CPF, Nome, Cidade, Bairro) VALUES ('0000001', 'Deadpool', 'Pau dos Ferros', 'Bairro João XXIII');

INSERT INTO tbPedidos ( Pedido, Data, ClienteCPF) VALUES ( 'AJDBESSD555', '2020-02-01', '0000001');

INSERT INTO tbPedidosItens (PedidoID, ProdutoID, Qtde, Unitario, Desconto) VALUES (
	(SELECT ID FROM tbPedidos WHERE ClienteCPF='0000001'),
	(SELECT ID FROM tbProdutos WHERE Codigo='0001'),
	10,
	(SELECT Preco FROM tbProdutos WHERE Codigo='0001'),
	0
);

INSERT INTO tbPedidosItens (PedidoID, ProdutoID, Qtde, Unitario, Desconto) VALUES (
	(SELECT ID FROM tbPedidos WHERE ClienteCPF='0000001'),
	(SELECT ID FROM tbProdutos WHERE Codigo='0002'),
	5,
	(SELECT Preco FROM tbProdutos WHERE Codigo='0002'),
	0
);

/* ******************************************************************************************************************************** */



/* *********************************************************** QUESTÃO 3 ********************************************************** */
/* ******************************************************************************************************************************** */

INSERT INTO tbClientes (CPF, Nome, Cidade, Bairro) VALUES ('0000002', 'Jinx', 'Pau dos Ferros', 'Bairro João XXIII');

INSERT INTO tbPedidos ( Pedido, Data, ClienteCPF) VALUES ( 'AJDBSLEMFMSS', '2020-02-01', '0000002');

INSERT INTO tbPedidosItens (PedidoID, ProdutoID, Qtde, Unitario, Desconto) VALUES (
	(SELECT ID FROM tbPedidos WHERE ClienteCPF='0000002'),
	(SELECT ID FROM tbProdutos WHERE Codigo='0002'),
	10,
	(SELECT Preco FROM tbProdutos WHERE Codigo='0002'),
	0);

INSERT INTO tbPedidosItens (PedidoID, ProdutoID, Qtde, Unitario, Desconto) VALUES (
	(SELECT ID FROM tbPedidos WHERE ClienteCPF='0000002'),
	(SELECT ID FROM tbProdutos WHERE Codigo='0003'),
	10,
	(SELECT Preco FROM tbProdutos WHERE Codigo='0003'),
	10);
	
/* ******************************************************************************************************************************** */


/* *********************************************************** QUESTÃO 4 ********************************************************** */

SELECT 
	tbClientes.CPF,
	tbClientes.Nome,
	tbClientes.Cidade,
	tbClientes.Bairro,
	tbPedidos.Pedido,
	tbPedidos.Data,
	tbProdutos.Codigo,
	tbProdutos.Descricao,
	tbPedidosItens.Qtde,
	tbPedidosItens.Unitario,
	tbPedidosItens.Desconto,
	(SELECT SUM(Qtde) AS TotalItens FROM tbPedidosItens)
FROM (((tbPedidosItens
	INNER JOIN tbPedidos ON tbPedidosItens.PedidoID = tbPedidos.ID)
	INNER JOIN tbProdutos ON tbPedidosItens.ProdutoID = tbProdutos.ID)
	INNER JOIN tbClientes ON tbPedidos.ClienteCPF = tbClientes.CPF)
WHERE tbPedidos.Data = '2020-02-01';

/* ******************************************************************************************************************************** */


/* *********************************************************** QUESTÃO 5 ********************************************************** */
/* ******************************************************************************************************************************** */

SELECT
	Result.Data AS Data,
	Result.Pedido AS Pedido,
	Result.CPF AS Cliente,
	Result.Nome AS Nome,
	Result.Cidade AS Cidade,
	SUM(Result.Qtde) AS TotalPedidos,
	SUM(Result.Qtde * Result.Unitario) AS TotalBruto,
	SUM(Result.Desconto) AS TotalDesconto,
	(SUM(Result.Qtde * Result.Unitario) - ((SUM(Result.Qtde * Result.Unitario) * SUM(Result.Desconto)) / 100)) AS TotalLiquido
	
FROM
	(SELECT * FROM ((tbClientes
	INNER JOIN tbPedidos ON tbPedidos.ClienteCPF = tbClientes.CPF)
	INNER JOIN tbPedidosItens ON tbPedidos.ID = tbPedidosItens.PedidoID)
	WHERE tbPedidos.Data >= '2020-02-01' AND tbPedidos.Data <= '2021-02-01'
	) AS Result

GROUP BY Data, Pedido, Cliente, Nome, Cidade


/* ******************************************************************************************************************************** */


/* *********************************************************** QUESTÃO 6 ********************************************************** */
/* ******************************************************************************************************************************** */

SELECT
	Result.Data AS Data,
	Result.CPF AS Cliente,
	Result.Cidade AS Cidade,
	SUM(Result.Qtde) AS TotalPedidos,
	SUM(Result.Qtde * Result.Unitario) AS TotalBruto,
	SUM(Result.Desconto) AS TotalDesconto,
	(SUM(Result.Qtde * Result.Unitario) - ((SUM(Result.Qtde * Result.Unitario) * SUM(Result.Desconto)) / 100)) AS TotalLiquido
	
FROM
	(SELECT * FROM ((tbClientes
	INNER JOIN tbPedidos ON tbPedidos.ClienteCPF = tbClientes.CPF)
	INNER JOIN tbPedidosItens ON tbPedidos.ID = tbPedidosItens.PedidoID)
	WHERE tbPedidos.Data >= '2020-02-01' AND tbPedidos.Data <= '2021-02-01'
	) AS Result

GROUP BY Data, Cliente, Cidade
ORDER BY Data DESC

/* ******************************************************************************************************************************** */


/* *********************************************************** QUESTÃO 7 ********************************************************** */
/* ******************************************************************************************************************************** */

SELECT
	Result.Nome AS Cliente,
	Result.Cidade AS Cidade,
	SUM(Result.Qtde) AS TotalPedidos,
	SUM(Result.Qtde * Result.Unitario) AS TotalBruto,
	SUM(Result.Desconto) AS TotalDesconto,
	(SUM(Result.Qtde * Result.Unitario) - ((SUM(Result.Qtde * Result.Unitario) * SUM(Result.Desconto)) / 100)) AS TotalLiquido
	
FROM
	(SELECT * FROM ((tbClientes
	INNER JOIN tbPedidos ON tbPedidos.ClienteCPF = tbClientes.CPF)
	INNER JOIN tbPedidosItens ON tbPedidos.ID = tbPedidosItens.PedidoID)
	WHERE tbPedidos.Data >= '2020-02-01' AND tbPedidos.Data <= '2021-02-01'
	) AS Result

GROUP BY Cliente, Cidade
ORDER BY Cliente

/* ******************************************************************************************************************************** */


/* *********************************************************** QUESTÃO 8 ********************************************************** */
/* ******************************************************************************************************************************** */

SELECT
	Result.Cidade AS Cidade,
	Result.Bairro AS Bairro,
	SUM(Result.Qtde) AS TotalPedidos,
	SUM(Result.Qtde * Result.Unitario) AS TotalBruto,
	SUM(Result.Desconto) AS TotalDesconto,
	(SUM(Result.Qtde * Result.Unitario) - ((SUM(Result.Qtde * Result.Unitario) * SUM(Result.Desconto)) / 100)) AS TotalLiquido
	
FROM
	(SELECT * FROM ((tbClientes
	INNER JOIN tbPedidos ON tbPedidos.ClienteCPF = tbClientes.CPF)
	INNER JOIN tbPedidosItens ON tbPedidos.ID = tbPedidosItens.PedidoID)
	WHERE tbClientes.Cidade = 'Pau dos Ferros'
	) AS Result

GROUP BY Cidade, Bairro
/* ******************************************************************************************************************************** */


/* *********************************************************** QUESTÃO 9 ********************************************************** */
/* ******************************************************************************************************************************** */

SELECT
	Result.Codigo AS Produto,
	Result.Grupo AS Grupo,
	SUM(Result.Qtde) AS TotalVendido,
	SUM(Result.Qtde * Result.Unitario) AS TotalBruto,
	SUM(Result.Desconto) AS TotalDesconto,
	(SUM(Result.Qtde * Result.Unitario) - ((SUM(Result.Qtde * Result.Unitario) * SUM(Result.Desconto)) / 100)) AS TotalLiquido,
	((SUM(Result.Qtde * Result.Unitario) - ((SUM(Result.Qtde * Result.Unitario) * SUM(Result.Desconto)) / 100)) / 3) AS ValorMedio
	
FROM
	(SELECT * FROM (((tbClientes
	INNER JOIN tbPedidos ON tbPedidos.ClienteCPF = tbClientes.CPF)
	INNER JOIN tbPedidosItens ON tbPedidos.ID = tbPedidosItens.PedidoID)
	INNER JOIN tbProdutos ON tbPedidosItens.ProdutoID = tbProdutos.ID)
	WHERE tbProdutos.Codigo = '0002'
	) AS Result

GROUP BY Produto, Grupo


/* ******************************************************************************************************************************** */


/* *********************************************************** QUESTÃO 10 ********************************************************* */
/* ******************************************************************************************************************************** */

DELETE FROM tbPedidosItens WHERE (SELECT ID FROM tbPedidos WHERE ClienteCPF='0000001')=PedidoID;
DELETE FROM tbPedidos WHERE ClienteCPF = '0000001';
DELETE FROM tbClientes WHERE CPF='0000001';

/* ******************************************************************************************************************************** */


/* *********************************************************** QUESTÃO 11 ********************************************************* */
/* ******************************************************************************************************************************** */

DELETE FROM tbPedidos WHERE (SELECT PedidoID FROM tbPedidosItens WHERE (SELECT ID FROM tbProdutos WHERE Codigo='0001')=ProdutoID)=ID;
DELETE FROM tbPedidosItens WHERE (SELECT ID FROM tbProdutos WHERE Codigo='0001')=ProdutoID;

/* ******************************************************************************************************************************** */
